---
version: '3.6'
services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - ./docker/redis/data:/data

  app-base:
    build:
      context: .
      target: base
    image: "${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}-base"

  app:
    build:
      cache_from:
        - "${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}-base"
      context: .
      args:
        os_packages: libpq5 sqlite3
    image: "${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"
    links:
      - redis
    ports:
      - '3000:3000'
    environment:
      RAILS_SERVE_STATIC_FILES: 1
      # SCHEDULE_IMPORT_CRON: '* * * * *'
    env_file:
      - ./.env

<% if app.sidekiq? -%>
  sidekiq:
    image: "${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"
    links:
      - redis
    env_file:
      - ./.env
    environment:
      RAILS_MAX_THREADS: 10
    command: bundle exec sidekiq -q <%= app.application_name %>_production_default
<% endif -%>

<% if app.grpc? -%>
  grpc:
    image: "${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"
    ports:
      - '50051:50051'
    env_file:
      - ./.env
    command: bundle exec rake grpc
<% endif -%>
