name: <%= Dir.pwd.split('/').pop(2).join('-') %>
root: <%= Dir.pwd %>

windows:
  - console:
      layout: main-vertical
      panes:
        - rails console
        - pwd
  - servers:
      layout: main-vertical
      panes:
        - rails server -b 0.0.0.0
        - cd ../frontend # && ember serve
  - rails:
      layout: main-horizontal
      panes:
        - pwd
  - ember:
      layout: main-horizontal
      panes:
        - cd ../frontend && pwd
  - data:
      layout: main-horizontal
      root: ~/data/<%= Dir.pwd.split('/').pop(2).first %>
      panes:
        - pwd
