name: <%= @app_name.gsub('.', '-') %>
root: <%= @parent_dir %>

windows:
  - console:
      layout: main-vertical
      root: <%= "#{@parent_dir}/#{@app_name}" %>
      panes:
        - rails console
        - pwd
  - servers:
      layout: main-vertical
      root: <%= @parent_dir %>
      panes:
        - cd <%= @app_name %> && rails server -b 0.0.0.0
        - cd recheck-web && ember serve
  - rails:
      layout: main-horizontal
      root: <%= "#{@parent_dir}/#{@app_name}" %>
      panes:
        - pwd
  - ember:
      layout: main-horizontal
      root: <%= "#{@parent_dir}/#{@app_name}" %>
      panes:
        - pwd
  - data:
      layout: main-horizontal
      root: ~/prepd/projects/<%= @app_name %>/data
      panes:
        - pwd
