---
version: '2'
services:
  web:
    build: .
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_NAME: todoapp
      DATABASE_USERNAME: todoapp
      DATABASE_PASSWORD: todoapp
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_PASSWORD: todoapp
      POSTGRES_DB: todos
