---
version: '2'
services:
<% if @packages.include?(:pg) -%>
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: <%= "#{ENV['USER']}" %>
      POSTGRES_PASSWORD: <%= "#{ENV['USER']}" %>
      POSTGRES_DB: <%= "#{@application_name}_development" %>
<% end -%>
<% if @packages.include?(:grpc) -%>
  grpc:
    build: .
    command: bundle exec rake grpc
    # volumes:
    #   - .:/app
    ports:
      - "50051:50051"
    links:
<% if @packages.include?(:pg) -%>
      - postgres
<% end -%>
    environment:
      DATABASE_HOST: postgres
      DATABASE_NAME: <%= "#{@application_name}_development" %>
      DATABASE_USERNAME: <%= "#{ENV['USER']}" %>
      DATABASE_PASSWORD: <%= "#{ENV['USER']}" %>
<% end -%>
  web:
    build: .
    command: bundle exec rails s -b 0.0.0.0
    # volumes:
    #   - .:/app
    ports:
      - "3000:3000"
    links:
<% if @packages.include?(:pg) -%>
      - postgres
<% end -%>
<% if @packages.include?(:grpc) -%>
      - grpc
<% end -%>
    environment:
      DATABASE_HOST: postgres
      DATABASE_NAME: <%= "#{@application_name}_development" %>
      DATABASE_USERNAME: <%= "#{ENV['USER']}" %>
      DATABASE_PASSWORD: <%= "#{ENV['USER']}" %>
